FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    mailutils \
    dnsutils \
    telnet \
    swaks \
    tcpdump \
    vim \
    net-tools \
    iputils-ping \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
