version: "2"

run:
  go: "1.24"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
      colors: true

linters:
  default: all
  disable:
    - cyclop
    - gocyclo
    - depguard
    - exhaustruct
    - funlen
    - godox
    - lll
    - nlreturn
    - nonamedreturns
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - ireturn

  settings:
    govet:
      enable-all: true
      settings:
        shadow:
          strict: false
    maintidx:
      under: 20
    misspell:
      locale: US
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: true

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
            - dupl
            - err113
            - gochecknoglobals
            - goconst
            - gocyclo
            - maintidx
            - mnd
        path: (.+)_test\.go
      - linters:
            - govet
        path: (.+)_test\.go
        text: 'fieldalignment:'
      - linters:
            - revive
        path: (.+)_test\.go
        text: 'unused-parameter:'
    paths:
      - frontend/

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - frontend/
  settings:
    gci:
        sections:
          - standard   # Standard library
          - default    # Third-party imports
          - prefix(github.com/arnald/forum)