# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lints and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: "${{ matrix.go-version }}.x"
        check-latest: true
        cache: false

    # https://github.com/actions/cache
    - name: cache tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: |
          .tools/
          ~/.cache/go-build
          ~/go/pkg
        key: ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ matrix.go-version }}-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile', 'scripts/tools.mk', '.github/workflows/ci.yml', 'tools/tools.go') }}
        restore-keys: |
          ci-tools-${{ runner.os }}-${{ runner.arch }}-${{ matrix.go-version }}

    - name: Install Tools
      if: steps.tools-cache.outputs.cache-hit != 'true'
      run: make tools

    - name: env
      run: |
        make --version
        echo ""
        make env

    - name: Run CI Pipeline
      run: make ci

    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        file: coverage.out
        flags: unittests